name: CI

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: clang-format check src folder
        uses: DoozyX/clang-format-lint-action@v0.5
        with:
          source: 'src'
      - name: clang-format check include folder
        uses: DoozyX/clang-format-lint-action@v0.5
        with:
          source: 'include'

  # TODO: clang-tidy job
